apiVersion: v1
kind: Service
metadata:
  name: mysqlservice
spec:
  type: LoadBalancer # loadbalancer for external, clusterIP for internal
  ports:
    - port: 3306 # port for the service itself
      targetPort: 3306 # target of the container port
      protocol: TCP
  selector:
    app: mysql # will attach this service to any pod with the label app: mysql