apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-2
  labels:
    app: nginx-2
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: nginx-2
  strategy: 
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25% 
  template:
    metadata:
      labels:
        app: nginx-2
        namespace: dev-manifest
    spec:
      containers:
      - name: nginx-2 
        image: nginx:latest