apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx 
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: nginx 
  strategy: 
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25% 
  template:
    metadata:
      labels:
        app: nginx 
        namespace: dev-cli
    spec:
      containers:
      - name: nginx 
        image: nginx:latest