apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer 
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: flask-app 
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
---
# create deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: flask-app
  strategy: 
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25% 
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: frontend
        image: reeceqa/python-frontend
        ports:
        - containerPort: 5000
      - name: backend
        image: reeceqa/python-backend
        ports:
        - containerPort: 5001