apiVersion: v1
kind: Secret
metadata:
    name: my-secret
data:
  mysql-password: cGFzc3dvcmQ= # echo -n "password" | base64
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: jenkins
  annotations:
    kubernetes.io/service-account.name: "jenkins"