apiVersion: v1 #different for different versions of k8s and different objects
kind: Pod #what object do we want to make.
metadata:
  name: nginx # pod name
  labels:
    app: nginx # attaching a key:value pair label
    author: Eloise
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    